// Builds content/icons.js from Iconify icon sets (dev dependencies), so the site ships only the
// handful of icons it uses. Everything is rendered in currentColor, so icons follow the theme.
//
//   npm run icons
//
// To add a tool: add a line to WANTED, run the command, then reference its key in content/data.js.
import { createRequire } from 'node:module';
import fs from 'node:fs';

const require = createRequire(import.meta.url);
const sets = {};
const set = (name) => (sets[name] ??= require(`@iconify-json/${name}/icons.json`));

// key, collection, icon name, display title
const WANTED = [
  ['react', 'simple-icons', 'react', 'React Native'],
  ['expo', 'simple-icons', 'expo', 'Expo'],
  ['javascript', 'simple-icons', 'javascript', 'JavaScript'],
  ['python', 'simple-icons', 'python', 'Python'],
  ['supabase', 'simple-icons', 'supabase', 'Supabase'],
  ['firebase', 'simple-icons', 'firebase', 'Firebase'],
  ['openai', 'simple-icons', 'openai', 'OpenAI API'],
  ['langchain', 'simple-icons', 'langchain', 'LangChain'],
  ['pinecone', 'logos', 'pinecone-icon', 'Pinecone'],
  ['github', 'simple-icons', 'github', 'GitHub'],
  ['postman', 'simple-icons', 'postman', 'Postman'],
  ['figma', 'simple-icons', 'figma', 'Figma'],
  ['canva', 'simple-icons', 'canva', 'Canva'],
  ['adobe', 'simple-icons', 'adobecreativecloud', 'Adobe Creative Cloud'],
  ['sheets', 'simple-icons', 'googlesheets', 'Google Sheets'],
  ['appsscript', 'simple-icons', 'googleappsscript', 'Apps Script'],
  ['discord', 'simple-icons', 'discord', 'Discord'],
  ['slack', 'simple-icons', 'slack', 'Slack'],
  ['trello', 'simple-icons', 'trello', 'Trello'],
  // No monochrome brand marks exist for these two, so they get a neutral glyph (not a fake logo).
  ['paystack', 'ri', 'bank-card-line', 'Paystack'],
  ['antigravity', 'ri', 'sparkling-line', 'Google Antigravity'],
];

const out = {};
for (const [key, col, name, title] of WANTED) {
  const s = set(col);
  const icon = s.icons[name];
  if (!icon) throw new Error(`Missing ${col}:${name}`);
  const w = icon.width ?? s.width ?? 24;
  const h = icon.height ?? s.height ?? 24;
  let body = icon.body;
  // single-colour marks: force currentColor so they follow the theme
  body = body.replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"');
  if (!/fill=/.test(body)) body = body.replace(/<path /g, '<path fill="currentColor" ');
  out[key] = { title, viewBox: `0 0 ${w} ${h}`, body };
}

const file =
  '// GENERATED by scripts/build-icons.mjs. Do not edit by hand.\n' +
  'export const icons = ' +
  JSON.stringify(out, null, 1) +
  ';\n';
fs.writeFileSync(new URL('../content/icons.js', import.meta.url), file);
console.log(`wrote ${Object.keys(out).length} icons, ${(file.length / 1024).toFixed(1)} KB`);
